name: CICD

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name:  Build and push back Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: raf4costa/back-todo:latest
          
      - name:  Build and push front Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: raf4costa/front-todo:latest
          
      - name: Test docker image
        run: docker run raf4costa/back-todo:latest npm test
     


  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: sa-east-1

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }} 
    
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }} 

      - name: Run containers
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.231.179.25 "echo 'Connected successfully'; sudo apt clean; docker stop $(docker ps -aq); docker rm $(docker ps -aq); docker pull raf4costa/back-todo:latest; docker run -d -p 3000:3000 raf4costa/back-todo:latest; docker pull raf4costa/front-todo:latest; docker run -d -p 80:5173 raf4costa/front-todo:latest"
          
        


      



      
