name: CICD

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: connect to ec2 and activate runner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/actions_runner/
            ./run.sh
      
  
  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull back image from docker hub
        run: docker pull eversonnascimento/back-todo:v1.0
      - name: Pull front image from docker hub
        run: docker pull limanascimento/supertodolist:v1.1
      - name: Check directory
        run: |
            pwd
            ls -la
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Run docker compose
        run: docker-compose up -d
     

## fix

